import { useState } from "react";
import "./App.css";

function App() {
  const [lessonStarted, setLessonStarted] = useState(false);

    const speak = (text) => {
        const utterance = new SpeechSynthesisUtterance(text);
            utterance.lang = "it-IT";
                utterance.rate = 0.85;
                    speechSynthesis.speak(utterance);
                      };

                        if (lessonStarted) {
                            return (
                                  <div className="app">
                                          <section className="card">
                                                    <h1>🇮🇹 1. lecke</h1>
                                                              <h2>Ciao</h2>
                                                                        <p>Szia</p>

                                                                                  <button onClick={() => speak("Ciao")}>🔊 Kiejtés</button>
                                                                                            <br /><br />
                                                                                                      <button onClick={() => setLessonStarted(false)}>⬅ Vissza</button>
                                                                                                              </section>
                                                                                                                    </div>
                                                                                                                        );
                                                                                                                          }

                                                                                                                            return (
                                                                                                                                <div className="app">
                                                                                                                                      <header className="hero">
                                                                                                                                              <div className="badge">🇮🇹 90 napos olasz tanfolyam</div>
                                                                                                                                                      <h1>Gábor Olasz Akadémia</h1>
                                                                                                                                                              <p>Tanulj olaszul naponta rövid, gyakorlati leckékkel.</p>
                                                                                                                                                                      <button className="primary" onClick={() => setLessonStarted(true)}>
                                                                                                                                                                                ▶ Mai lecke indítása
                                                                                                                                                                                        </button>
                                                                                                                                                                                              </header>

                                                                                                                                                                                                    <main className="dashboard">
                                                                                                                                                                                                            <section className="card big">
                                                                                                                                                                                                                      <h2>🔥 Mai lecke</h2>
                                                                                                                                                                                                                                <p className="muted">1. lecke – Köszönések és bemutatkozás</p>

                                                                                                                                                                                                                                          <div className="word">
                                                                                                                                                                                                                                                      <span>
                                                                                                                                                                                                                                                                    <b>Ciao</b>
                                                                                                                                                                                                                                                                                  <small>Szia • csáó</small>
                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                          <button onClick={() => speak("Ciao")}>🔊</button>
                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                              <div className="word">
                                                                                                                                                                                                                                                                                                                                          <span>
                                                                                                                                                                                                                                                                                                                                                        <b>Buongiorno</b>
                                                                                                                                                                                                                                                                                                                                                                      <small>Jó napot • buon-dzsor-no</small>
                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={() => speak("Buongiorno")}>🔊</button>
                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                                                                                                                                                                                                        <section className="grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mini"><h3>📚 Leckék</h3><p>1 / 90 kész</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mini"><h3>🧠 Anki</h3><p>5 kártya</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mini"><h3>🏆 XP</h3><p>25 pont</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="mini"><h3>🔥 Sorozat</h3><p>1 nap</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <section className="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2>📈 Haladás</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="progress"><div className="bar"></div></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="muted">Cél: használható társalgási olasz 90 nap alatt.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default App;